version: 2
jobs:
  contracts:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: run all contract tests
          command: |
            make test-contracts

workflows:
  version: 2
  my-workflow:
    jobs:
      - contracts
